name: Deploy Script

on:
  workflow_dispatch:
  push:
    branches: [master, main, develop]

  release:
    types: [published]
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install clasp
        id: install-clasp
        run: sudo npm install @google/clasp -g

      - name: Write CLASPRC_JSON secret to .clasprc.json file
        id: write-clasprc
        run: echo "$CLASPRC_JSON_SECRET" >> ~/.clasprc.json
        env:
          CLASPRC_JSON_SECRET: ${{ secrets.CLASPRC_JSON }}

      - name: Check clasp login status
        id: clasp_login
        run: clasp login --status

      - name: Save current .clasprc.json contents to CLASPRC_JSON environment variable
        id: save-clasprc
        run: |
          echo "CLASPRC_JSON_FILE=$(cat ~/.clasprc.json)" >> $GITHUB_ENV
          echo "CLASPRC_JSON_SECRET=$CLASPRC_JSON_SECRET" >> $GITHUB_ENV
        env:
          CLASPRC_JSON_SECRET: ${{ secrets.CLASPRC_JSON }}

      # - name: Check if .clasprc.json has changed from CLASPRC_JSON secret
      #   id: check_clasprc_changed
      #   run: |
      #     if ["$(cat ~/.clasprc.json)" != "$CLASPRC_JSON"]
      #     then
      #          echo "UPDATED_CLASPRC_JSON=YES" >> $GITHUB_ENV
      #     fi
      #   env:
      #     CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}

      - name: Save updated CLASPRC_JSON environment variable to CLASPRC_JSON repo secret
        if: ${{ env.CLASPRC_JSON_FILE != env.CLASPRC_JSON_SECRET  }}
        id: set-clasprc-secret
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: "CLASPRC_JSON"
          value: ${{ env.CLASPRC_JSON_FILE }}
          repository: ${{ github.repository }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Checkout repo
        if: ${{github.event_name	!= 'schedule' }}
        uses: actions/checkout@v2

      - name: Set scriptId in .clasp.json file
        id: set-script-id
        run: jq '.scriptId = "${{env.SCRIPT_ID}}"' .clasp.json > /tmp/.clasp.json && mv /tmp/.clasp.json .clasp.json
        if: ${{ github.event_name	!= 'schedule' && env.SCRIPT_ID}}
        env:
          SCRIPT_ID: ${{secrets.SCRIPT_ID}}

      - name: Push script to scripts.google.com
        id: clasp-push
        if: ${{ github.event_name	!= 'schedule'}}
        run: clasp push -f

      - name: Deploy Script
        id: clasp-deploy
        if: ${{env.DEPLOYMENT_ID}}
        # if: ${{ secrets.DEPLOYMENT_ID && github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'}
        run: clasp deploy -i "$DEPLOYMENT_ID" -d "$GITHUB_REF"
        env:
          DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}
