# This workflow deploys the project to Google Apps Script
# 1
name: Deploy Google Apps Script

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches: [master, main, develop]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # - name: List Files
      #   run: ls -a

      # - name: Setup NodeJs
      #   uses: actions/setup-node@v1

      - name: Install clasp
        run: sudo npm install @google/clasp -g

      - name: Write .clasprc.json file
        run: echo "$CLASPRC_JSON" >> ~/.clasprc.json
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}

      - name: Check clasp login status
        run: clasp login --status

      # - name: Install jq
      #   run: sudo apt-get install jq
      #   if: ${{env.scriptId}}

      - name: Set ScriptId
        run: jq '.scriptId = "${{env.scriptId}}"' .clasp.json > /tmp/.clasp.json && mv /tmp/.clasp.json .clasp.json
        if: ${{env.scriptId}}
        env:
          scriptId: ${{secrets.SCRIPT_ID}}

      - name: Push script to scripts.google.com
        run: clasp push -f

      - name: Deploy Script
        # if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        run: clasp deploy -i "$DEPLOYMENT_ID" -d "$GITHUB_REF"
        env:
          DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}

      - name: Check if .clasprc.json has changed
        if: ${{ always() }}
        run: '[[ "$(cat ~/.clasprc.json)" == "$CLASPRC_JSON" ]] && echo ".clasprc.json has not changed" || echo ".clasprc.json has changed"'
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}

      - name: Save current .clasprc.json contents to CLASPRC_JSON environment variable
        if: ${{ always() }}
        run: echo "CLASPRC_JSON=$(cat ~/.clasprc.json)" >> $GITHUB_ENV

      - name: Save CLASPRC_JSON environment variable to CLASPRC_JSON repo secret
        uses: hmanzur/actions-set-secret@v2.0.0
        if: ${{ always() }}
        with:
          name: "CLASPRC_JSON"
          value: ${{ env.CLASPRC_JSON }}
          repository: ${{ github.repository }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
