# This workflow deploys the project to Google
name: Deploy App Script

on:
  push:
    branches: [ master ]

jobs:
  
  deploy:
    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Setup NodeJs
      uses: actions/setup-node@v1
      
    - name: Install clasp
      run: npm install @google/clasp -g
      
    - name: Install Puppeteer
      run: npm i puppeteer


    - name: Test deploy.js
      run: node deploy.js
      env:
        GOOGLE_USER: ${{ secrets.GOOGLE_USER }}
        GOOGLE_PASS: ${{ secrets.GOOGLE_PASS }}
        LOGGING_ENABLED: true
      
    - name: Login to clasp
      run: node deploy.js | clasp login --no-localhost
      env:
        GOOGLE_USER: ${{ secrets.GOOGLE_USER }}
        GOOGLE_PASS: ${{ secrets.GOOGLE_PASS }}

    - name: Check login status
      run: clasp login --status
      
    
