# This workflow deploys the project to Google
name: Deploy App Script

on:
  push:
    branches: [ master, clasprc-secret ]
jobs:
  
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Setup NodeJs
      uses: actions/setup-node@v1
      
    - name: Install clasp
      run: npm install @google/clasp -g
      
    - name: Write .clasprc.json file
      run: echo "$CLASPRC_JSON" >> ~/.clasprc.json-wrong-file
      env:
        CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
    - name: Check clasp login status
      run: clasp login --status
      
    - name: Push Script
      run: clasp push
      
    - name: Save .clasprc.json to repo secret
      if: ${{ always() }}
      run: echo "always run this"
    
      
    
