# This workflow deploys the project to Google Apps Script
# 1
name: Deploy Google Apps Script

on:
  workflow_dispatch:
  push:
    branches: [master, clasprc-secret]
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      scriptId: ${{secrets.SCRIPT_ID}}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: List Files
        run: ls -a

      - name: Setup NodeJs
        uses: actions/setup-node@v1

      - name: Install clasp
        run: npm install @google/clasp -g

      - name: Write .clasprc.json file
        run: echo "$CLASPRC_JSON" >> ~/.clasprc.json
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}

      - name: Check clasp login status
        run: clasp login --status

      - name: Install jq
        run: sudo apt-get install jq
        if: ${{env.scriptId}}

      - name: Set ScriptId
        run: jq '.scriptId = "${{env.scriptId}}"' .clasp.json > /tmp/.clasp.json && mv /tmp/.clasp.json .clasp.json
        if: ${{env.scriptId}}

      - name: Push script to scripts.google.com
        run: clasp push -f

      - name: Save current .clasprc.json contents to CLASPRC_JSON environment variable
        if: ${{ always() }}
        run: echo "CLASPRC_JSON=$(cat ~/.clasprc.json)" >> $GITHUB_ENV

      - name: Save CLASPRC_JSON environment variable to CLASPRC_JSON repo secret
        uses: hmanzur/actions-set-secret@v2.0.0
        if: ${{ always() }}
        with:
          name: "CLASPRC_JSON"
          value: ${{ env.CLASPRC_JSON }}
          repository: ${{ github.repository }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
