# This workflow deploys the project to Google
name: Deploy App Script

on:
  push:
    branches: [ master ]


jobs:
  
  deploy:
    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Setup NodeJs
      uses: actions/setup-node@v1
      
    - name: Install clasp
      run: npm install @google/clasp -g
