name: Refresh Login

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SUN"
  push:
    branches: [master, main, develop]
jobs:
  refresh-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: "Init clasp"
        uses: "./init-clasp"
